default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    sync_code_signing(type: "appstore")
    build_app(
      scheme: "Runner",
      export_method: "app-store"
    )
    upload_to_testflight
  end
end


